services:
  clock-1: &clock
    build: ./api
    ports:
      - "5310:5310"
    environment:
      - id_clock=0
      - clock_1=http://192.168.0.10:5310
      - clock_2=http://192.168.0.11:5310
      - clock_3=http://192.168.0.12:5310
      - clock_4=http://192.168.0.13:5310
    networks:
      clocks_network:
        ipv4_address: 192.168.0.10

  clock-2:
    <<: *clock
    ports:
      - "5311:5310"
    build: ./api
    environment:
      - id_clock=1
      - clock_1=http://192.168.0.10:5310
      - clock_2=http://192.168.0.11:5310
      - clock_3=http://192.168.0.12:5310
      - clock_4=http://192.168.0.13:5310
    networks:
      clocks_network:
        ipv4_address: 192.168.0.11

  clock-3:
    <<: *clock
    ports:
      - "5312:5310"
    build: ./api
    environment:
      - id_clock=2
      - clock_1=http://192.168.0.10:5310
      - clock_2=http://192.168.0.11:5310
      - clock_3=http://192.168.0.12:5310
      - clock_4=http://192.168.0.13:5310
    networks:
      clocks_network:
        ipv4_address: 192.168.0.12

  clock-4:
    <<: *clock
    ports:
      - "5313:5310"
    environment:
      - id_clock=3
      - clock_1=http://192.168.0.10:5310
      - clock_2=http://192.168.0.11:5310
      - clock_3=http://192.168.0.12:5310
      - clock_4=http://192.168.0.13:5310
    networks:
      clocks_network:
        ipv4_address: 192.168.0.13

networks:
  clocks_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24