services:
  clock-1: &clock
    build: ./api
    ports:
      - "5310:5310"
    environment:
      - id_clock=1
      - clock_1="http://localhost:5310"
      - clock_2="http://localhost:5311"
      - clock_3="http://localhost:5312"
      - clock_4="http://localhost:5313"
    networks:
      clocks_network:

  clock-2:
    <<: *clock
    ports:
      - "5311:5310"
    build: ./api
    environment:
      - id_clock=2
    networks:
      clocks_network:

  clock-3:
    <<: *clock
    ports:
      - "5312:5310"
    build: ./api
    environment:
      - id_clock=3
    networks:
      clocks_network:

  clock-4:
    <<: *clock
    ports:
      - "5313:5310"
    environment:
      - id_clock=4
    networks:
      clocks_network:

networks:
  clocks_network:
    driver: bridge